name: Deploy React App

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
